/**
 * iOS Notes formatters (plans/ios/apps/notes.md, `IOS-NOTES-02` "unit: generated note snapshots"): the notes are
 * derived from their inputs only — a fixture in, the exact blocks out; no career fact is typed in the formatter.
 */
import { describe, expect, it } from 'vitest';
import {
  buildNotes,
  countMatches,
  meterLabel,
  noteMatches,
  notesWithTag,
  noteStrings,
  pinnedNotes,
  recurringTools,
  shortDate,
  shouldCollapse,
  skillMeta,
  splitMatches,
  tagOf,
  type NotesInput,
} from '@/components/os/ios/apps/notes-model';
import { getExperience, getPerson, getProjects, getSkills } from '@/data/selectors';

const FIXTURE: NotesInput = {
  skills: [
    {
      id: 'front',
      label: 'Frontend',
      items: [
        { name: 'Zeta', level: 4, years: 6 },
        { name: 'Quill', level: 2 },
        { name: 'Ember', years: 1 },
      ],
    },
    { id: 'ops', label: 'Operations', items: [{ name: 'Harbor', level: 1, years: 2 }, { name: 'Kiln' }] },
    { id: 'empty', label: 'Nothing here', items: [] },
  ],
  person: { summary: ['First paragraph about a fixture person.', 'Second paragraph.'] },
  experience: [
    { highlights: ['Led fixture work.', 'Second highlight.'], stack: ['Zeta', 'Harbor'] },
    { highlights: [], stack: ['Zeta', 'Kiln'] },
  ],
  projects: [
    { slug: 'alpha', name: 'Alpha', stack: ['Zeta', 'Kiln'] },
    { slug: 'beta', name: 'Beta', stack: ['Harbor'] },
    { slug: 'gamma', name: 'Gamma', stack: [] },
  ],
};

describe('IOS-NOTES-02 notes are generated by formatters from the data', () => {
  it('generated note snapshots: pinned Skills + How I work, then Stack by project and Currently learning', () => {
    const notes = buildNotes(FIXTURE);
    expect(notes.map((note) => [note.id, note.title, note.pinned])).toEqual([
      ['skills', 'Skills', true],
      ['how-i-work', 'How I work', true],
      ['stack', 'Stack by project', false],
      ['learning', 'Currently learning', false],
    ]);
    expect(notes).toMatchInlineSnapshot(`
      [
        {
          "blocks": [
            {
              "kind": "heading",
              "text": "Frontend",
            },
            {
              "group": "front",
              "items": [
                {
                  "level": 4,
                  "name": "Zeta",
                  "years": 6,
                },
                {
                  "level": 2,
                  "name": "Quill",
                },
                {
                  "name": "Ember",
                  "years": 1,
                },
              ],
              "kind": "checklist",
            },
            {
              "kind": "heading",
              "text": "Operations",
            },
            {
              "group": "ops",
              "items": [
                {
                  "level": 1,
                  "name": "Harbor",
                  "years": 2,
                },
                {
                  "name": "Kiln",
                },
              ],
              "kind": "checklist",
            },
          ],
          "id": "skills",
          "pinned": true,
          "preview": "Frontend: Zeta, Quill, Ember",
          "tags": [
            "front",
            "ops",
          ],
          "title": "Skills",
        },
        {
          "blocks": [
            {
              "kind": "paragraph",
              "text": "First paragraph about a fixture person.",
            },
            {
              "kind": "paragraph",
              "text": "Second paragraph.",
            },
            {
              "kind": "heading",
              "text": "What I keep doing",
            },
            {
              "items": [
                "Led fixture work.",
              ],
              "kind": "bullets",
            },
            {
              "kind": "heading",
              "text": "Tools I keep reaching for",
            },
            {
              "items": [
                "Zeta — 3 roles and projects",
                "Harbor — 2 roles and projects",
                "Kiln — 2 roles and projects",
              ],
              "kind": "bullets",
            },
          ],
          "id": "how-i-work",
          "pinned": true,
          "preview": "First paragraph about a fixture person.",
          "tags": [
            "zeta",
            "harbor",
            "kiln",
          ],
          "title": "How I work",
        },
        {
          "blocks": [
            {
              "caption": "Technologies used in each project",
              "columns": [
                "Project",
                "Technologies",
              ],
              "kind": "table",
              "rows": [
                {
                  "name": "Alpha",
                  "slug": "alpha",
                  "stack": [
                    "Zeta",
                    "Kiln",
                  ],
                },
                {
                  "name": "Beta",
                  "slug": "beta",
                  "stack": [
                    "Harbor",
                  ],
                },
              ],
            },
          ],
          "id": "stack",
          "pinned": false,
          "preview": "Alpha, Beta",
          "tags": [],
          "title": "Stack by project",
        },
        {
          "blocks": [
            {
              "items": [
                "Quill",
                "Harbor",
              ],
              "kind": "bullets",
            },
          ],
          "id": "learning",
          "pinned": false,
          "preview": "Quill, Harbor",
          "tags": [
            "front",
            "ops",
          ],
          "title": "Currently learning",
        },
      ]
    `);
  });

  it('no skill at level ≤ 2 → "Currently learning" is absent (levels are never inferred)', () => {
    const skills = FIXTURE.skills.map((group) => ({
      ...group,
      items: group.items.map(({ name, years }) => ({ name, ...(years ? { years } : {}) })),
    }));
    const notes = buildNotes({ ...FIXTURE, skills });
    expect(notes.map((note) => note.id)).toEqual(['skills', 'how-i-work', 'stack']);
    // No level published → no meter label anywhere.
    const lines = notes[0]!.blocks.flatMap((block) => (block.kind === 'checklist' ? block.items : []));
    expect(lines.map(meterLabel)).toEqual([null, null, null, null, null]);
  });

  it('no hard-coded facts: every string comes from the inputs (plus the notes’ own UI words)', () => {
    const ui = new Set(['Project', 'Technologies', 'What I keep doing', 'Tools I keep reaching for']);
    const inputs = new Set<string>([
      ...FIXTURE.skills.flatMap((group) => [group.label, ...group.items.map((item) => item.name)]),
      ...FIXTURE.person.summary,
      ...FIXTURE.experience.flatMap((role) => role.highlights),
      ...FIXTURE.projects.flatMap((project) => [project.name, project.stack.join(', ')]),
    ]);
    for (const note of buildNotes(FIXTURE))
      for (const text of noteStrings(note)) {
        if (ui.has(text) || inputs.has(text) || text.startsWith('#')) continue;
        // Derived lines name an input tool and a count.
        expect(text).toMatch(/^(Zeta|Harbor|Kiln) — \d+ roles and projects$/);
      }
    // The real portfolio's facts never leak into a fixture's notes.
    const person = getPerson();
    const all = buildNotes(FIXTURE).flatMap(noteStrings).join('\n');
    expect(all).not.toContain(person.name);
    for (const project of getProjects()) expect(all).not.toContain(project.name);
  });

  it('the real data builds the notes the app shows (derived, not typed)', () => {
    const notes = buildNotes({
      skills: getSkills(),
      person: getPerson(),
      experience: getExperience(),
      projects: getProjects(),
    });
    const skills = notes.find((note) => note.id === 'skills')!;
    const headings = skills.blocks
      .filter((block) => block.kind === 'heading')
      .map((block) => (block as { text: string }).text);
    expect(headings).toEqual(
      getSkills()
        .filter((group) => group.items.length)
        .map((group) => group.label),
    );
    const table = notes.find((note) => note.id === 'stack')!.blocks[0]!;
    expect(table.kind === 'table' && table.rows.map((row) => row.slug)).toEqual(
      getProjects()
        .filter((project) => project.stack.length)
        .map((project) => project.slug),
    );
    expect(notes.find((note) => note.id === 'how-i-work')!.blocks[0]).toEqual({
      kind: 'paragraph',
      text: getPerson().summary[0],
    });
    // The owner has published no ratings → no "Currently learning" note.
    const anyLevel = getSkills().some((group) =>
      group.items.some((item) => item.level !== undefined && item.level <= 2),
    );
    expect(notes.some((note) => note.id === 'learning')).toBe(anyLevel);
    expect(pinnedNotes(notes)).toEqual([
      { id: 'skills', title: 'Skills' },
      { id: 'how-i-work', title: 'How I work' },
    ]);
  });

  it('meters: "Name: n of 5, y years" only with a level; visible text equivalent', () => {
    expect(meterLabel({ name: 'TypeScript', level: 4, years: 6 })).toBe('TypeScript: 4 of 5, 6 years');
    expect(meterLabel({ name: 'Go', level: 3, years: 1 })).toBe('Go: 3 of 5, 1 year');
    expect(meterLabel({ name: 'Go', level: 3 })).toBe('Go: 3 of 5');
    expect(meterLabel({ name: 'Go', years: 3 })).toBeNull();
    expect(skillMeta({ name: 'TypeScript', level: 4, years: 6 })).toBe('4 of 5 · 6 yrs');
    expect(skillMeta({ name: 'Go', years: 1 })).toBe('1 yr');
    expect(skillMeta({ name: 'Go' })).toBe('');
  });

  it('tags, recurring tools, tag filter and collapse threshold', () => {
    expect(tagOf('C++')).toBe('cpp');
    expect(tagOf('Backend & microservices')).toBe('backend-microservices');
    expect(tagOf('C#')).toBe('csharp');
    expect(recurringTools(FIXTURE)).toEqual([
      { name: 'Zeta', count: 3 },
      { name: 'Harbor', count: 2 },
      { name: 'Kiln', count: 2 },
    ]);
    const notes = buildNotes(FIXTURE);
    expect(notesWithTag(notes, 'ops').map((note) => note.id)).toEqual(['skills', 'learning']);
    expect(notesWithTag(notes, 'zeta').map((note) => note.id)).toEqual(['how-i-work']);
    expect(notesWithTag(notes, null)).toHaveLength(4);
    expect(shouldCollapse(FIXTURE.skills)).toBe(false);
    const many = [{ id: 'x', label: 'X', items: Array.from({ length: 31 }, (_, i) => ({ name: `S${i}` })) }];
    expect(shouldCollapse(many)).toBe(true);
  });
});

describe('IOS-NOTES-03 find in note: matching and counting', () => {
  it('counts case-insensitive, non-overlapping matches in reading order; splits for <mark>', () => {
    const [skills] = buildNotes(FIXTURE);
    expect(countMatches(skills!, 'e')).toBeGreaterThan(0);
    expect(countMatches(skills!, 'ZETA')).toBe(1);
    expect(countMatches(skills!, 'nope')).toBe(0);
    expect(countMatches(skills!, '   ')).toBe(0);
    expect(splitMatches('Zeta and zeta', 'zeta')).toEqual([
      { text: 'Zeta', match: true },
      { text: ' and ', match: false },
      { text: 'zeta', match: true },
    ]);
    expect(splitMatches('aaa', 'aa')).toEqual([
      { text: 'aa', match: true },
      { text: 'a', match: false },
    ]);
  });

  it('list search matches titles and body text', () => {
    const notes = buildNotes(FIXTURE);
    expect(notes.filter((note) => noteMatches(note, 'stack')).map((note) => note.id)).toEqual(['stack']);
    expect(notes.filter((note) => noteMatches(note, 'fixture person')).map((note) => note.id)).toEqual(['how-i-work']);
    expect(notes.filter((note) => noteMatches(note, ''))).toHaveLength(4);
  });

  it('list dates read like Notes (M/D/YY)', () => {
    expect(shortDate('2026-09-21')).toBe('9/21/26');
    expect(shortDate('2026-03')).toBe('3/1/26');
  });
});
