/**
 * Command behaviours, keyed by the names in the command table (`manifest.ts`). A unit test asserts both lists are the
 * same set, so `help`, `man`, `which`, `/usr/bin` and completion never advertise a command that does not run.
 */
import type { Command } from '../types';
import { about, contact, education, experience, mail, projects, resume, skills, whoami } from './about';
import { cmatrix, cowsay, emacs, fortune, nano, neofetch, rm, sudo, vi, vim } from './eggs';
import {
  cat,
  cd,
  chmod,
  cp,
  echo,
  find,
  grep,
  head,
  less,
  ls,
  mkdir,
  mv,
  open,
  pwd,
  rmdir,
  sort,
  tail,
  touch,
  tree,
  uniq,
  wc,
} from './fs';
import { alias, clear, exit, help, history, man, type, which } from './shell';

export const COMMAND_TABLE: Readonly<Record<string, Command>> = {
  ls,
  cd,
  pwd,
  tree,
  find,
  grep,
  open,
  less,
  whoami,
  about,
  projects,
  experience,
  education,
  skills,
  contact,
  resume,
  mail,
  cat,
  head,
  tail,
  wc,
  sort,
  uniq,
  echo,
  help,
  man,
  history,
  clear,
  which,
  type,
  alias,
  exit,
  touch,
  mkdir,
  rmdir,
  cp,
  mv,
  chmod,
  sudo,
  neofetch,
  vim,
  vi,
  nano,
  emacs,
  rm,
  cowsay,
  fortune,
  cmatrix,
};
