/**
 * Official artwork sources — shared/11 `ASSET-INBOX-01`. Each entry maps a raw file dropped in `assets-inbox/` to a
 * manifest id, with provenance for the Legal surface. Missing files are skipped (the original baseline renders).
 * Retrieval details live in assets-inbox/README.md. All marks belong to their owners and are used referentially.
 *
 * transform:
 *   'none'              keep the artwork as delivered (pre-shaped / free-form icons, avatars)
 *   'mac-squircle'      full-bleed square → macOS icon grid (squircle with the standard 10 % inset)
 *   'mac-squircle-crop' white-backed artwork → scaled 1.26 and cropped to the squircle
 *   'hue-green'         derived variant: hue-rotated copy (used only while the real file is missing)
 */
const APPLE = {
  owner: 'Apple Inc.',
  terms: 'Trademark and artwork of Apple Inc.; used referentially to identify the app. No affiliation.',
};
const GOOGLE = {
  owner: 'Google LLC',
  terms: 'Trademark and artwork of Google LLC; used referentially to identify the app. No affiliation.',
};
const MICROSOFT = {
  owner: 'Microsoft Corporation',
  terms: 'Trademark and artwork of Microsoft Corporation; used referentially to identify the app. No affiliation.',
};
const GITHUB = {
  owner: 'GitHub, Inc.',
  terms: 'Trademark and artwork of GitHub, Inc.; used referentially to identify the app. No affiliation.',
};
const NETFLIX = {
  owner: 'Netflix, Inc.',
  terms:
    'Artwork of Netflix, Inc.; used referentially for a profile picker. No affiliation; the Netflix name and logo never appear.',
};
const RETRIEVED = '2026-09-21';

const appStore = (id) => `https://apps.apple.com/app/id${id}`;
const play = (pkg) => `https://play.google.com/store/apps/details?id=${pkg}`;
const commons = (file) => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file)}`;

/** @typedef {{ id: string, file: string, kind: 'app-icon'|'system-icon'|'avatar'|'audio'|'wallpaper', sizes?: number[], transform?: string, monochrome?: boolean, derivedFrom?: string, owner: string, terms: string, sourceUrl: string, retrieved: string, label: string }} AssetSource */

/** @type {AssetSource[]} */
export const ASSET_SOURCES = [
  // macOS — Dock / Finder sidebar / Launchpad
  {
    id: 'app.macos.finder',
    file: 'icons/system/finder.png',
    kind: 'app-icon',
    sizes: [64, 128],
    ...APPLE,
    sourceUrl: commons('Finder Icon macOS Big Sur.png'),
    retrieved: RETRIEVED,
    label: 'Finder',
  },
  {
    id: 'app.macos.safari',
    file: 'icons/appstore/safari.png',
    kind: 'app-icon',
    sizes: [64, 128],
    transform: 'mac-squircle',
    ...APPLE,
    sourceUrl: appStore(1146562112),
    retrieved: RETRIEVED,
    label: 'Safari',
  },
  {
    id: 'app.macos.github',
    file: 'icons/appstore/github.png',
    kind: 'app-icon',
    sizes: [64, 128],
    transform: 'mac-squircle',
    ...GITHUB,
    sourceUrl: appStore(1477376905),
    retrieved: RETRIEVED,
    label: 'GitHub',
  },
  {
    id: 'app.macos.preview',
    file: 'icons/system/macos-preview.png',
    kind: 'app-icon',
    sizes: [64, 128],
    ...APPLE,
    sourceUrl: 'https://support.apple.com/guide/preview/welcome/mac',
    retrieved: RETRIEVED,
    label: 'Preview',
  },
  {
    id: 'app.macos.mail',
    file: 'icons/appstore/mail.png',
    kind: 'app-icon',
    sizes: [64, 128],
    transform: 'mac-squircle',
    ...APPLE,
    sourceUrl: appStore(1108187098),
    retrieved: RETRIEVED,
    label: 'Mail',
  },
  {
    id: 'app.macos.vscode',
    file: 'icons/desktop/vscode.png',
    kind: 'app-icon',
    sizes: [64, 128],
    owner: 'Microsoft Corporation',
    terms: MICROSOFT.terms,
    sourceUrl: 'https://code.visualstudio.com/brand',
    retrieved: RETRIEVED,
    label: 'Visual Studio Code',
  },
  {
    id: 'app.macos.terminal',
    file: 'icons/system/macos-terminal.png',
    kind: 'app-icon',
    sizes: [64, 128],
    transform: 'mac-squircle-crop',
    ...APPLE,
    sourceUrl: commons('Terminalicon2.png'),
    retrieved: RETRIEVED,
    label: 'Terminal',
  },
  {
    id: 'app.macos.settings',
    file: 'icons/system/macos-system-settings.png',
    kind: 'app-icon',
    sizes: [64, 128],
    ...APPLE,
    sourceUrl: 'https://support.apple.com/guide/mac-help/change-system-settings-mh15217/mac',
    retrieved: RETRIEVED,
    label: 'System Settings',
  },

  // Windows 11 — taskbar / Start (free-form icons, no tile)
  {
    id: 'app.windows.explorer',
    file: 'icons/windows/explorer.png',
    kind: 'app-icon',
    sizes: [32, 64],
    ...MICROSOFT,
    sourceUrl: 'https://learn.microsoft.com/windows/apps/design/style/iconography/app-icon-design',
    retrieved: RETRIEVED,
    label: 'File Explorer',
  },
  {
    id: 'app.windows.edge',
    file: 'icons/windows/edge.svg',
    kind: 'app-icon',
    ...MICROSOFT,
    sourceUrl: 'https://www.microsoft.com/edge',
    retrieved: RETRIEVED,
    label: 'Microsoft Edge',
  },
  {
    id: 'app.windows.github',
    file: 'icons/desktop/github-mark.svg',
    kind: 'app-icon',
    monochrome: true,
    ...GITHUB,
    sourceUrl: 'https://github.com/primer/octicons',
    retrieved: RETRIEVED,
    label: 'GitHub',
  },
  {
    id: 'app.windows.outlook',
    file: 'icons/windows/outlook.svg',
    kind: 'app-icon',
    ...MICROSOFT,
    sourceUrl: 'https://www.microsoft.com/microsoft-365/outlook',
    retrieved: RETRIEVED,
    label: 'Outlook',
  },
  {
    id: 'app.windows.vscode',
    file: 'icons/desktop/vscode.png',
    kind: 'app-icon',
    sizes: [32, 64],
    ...MICROSOFT,
    sourceUrl: 'https://code.visualstudio.com/brand',
    retrieved: RETRIEVED,
    label: 'Visual Studio Code',
  },
  {
    id: 'app.windows.terminal',
    file: 'icons/desktop/windows-terminal.png',
    kind: 'app-icon',
    sizes: [32, 64],
    owner: 'Microsoft Corporation',
    terms: `${MICROSOFT.terms} Source repository is MIT-licensed.`,
    sourceUrl: 'https://github.com/microsoft/terminal',
    retrieved: RETRIEVED,
    label: 'Terminal',
  },
  {
    id: 'app.windows.settings',
    file: 'icons/windows/settings.svg',
    kind: 'app-icon',
    ...MICROSOFT,
    sourceUrl: 'https://support.microsoft.com/windows',
    retrieved: RETRIEVED,
    label: 'Settings',
  },

  // iOS — Home Screen (full-bleed squares; the squircle mask is applied by the UI)
  {
    id: 'app.ios.safari',
    file: 'icons/appstore/safari.png',
    kind: 'app-icon',
    sizes: [120, 180],
    ...APPLE,
    sourceUrl: appStore(1146562112),
    retrieved: RETRIEVED,
    label: 'Safari',
  },
  {
    id: 'app.ios.github',
    file: 'icons/appstore/github.png',
    kind: 'app-icon',
    sizes: [120, 180],
    ...GITHUB,
    sourceUrl: appStore(1477376905),
    retrieved: RETRIEVED,
    label: 'GitHub',
  },
  {
    id: 'app.ios.files',
    file: 'icons/appstore/files.png',
    kind: 'app-icon',
    sizes: [120, 180],
    ...APPLE,
    sourceUrl: appStore(1232058109),
    retrieved: RETRIEVED,
    label: 'Files',
  },
  {
    id: 'app.ios.notes',
    file: 'icons/appstore/notes.png',
    kind: 'app-icon',
    sizes: [120, 180],
    ...APPLE,
    sourceUrl: appStore(1110145109),
    retrieved: RETRIEVED,
    label: 'Notes',
  },
  {
    id: 'app.ios.mail',
    file: 'icons/appstore/mail.png',
    kind: 'app-icon',
    sizes: [120, 180],
    ...APPLE,
    sourceUrl: appStore(1108187098),
    retrieved: RETRIEVED,
    label: 'Mail',
  },
  {
    id: 'app.ios.messages',
    file: 'icons/appstore/messages.png',
    kind: 'app-icon',
    sizes: [120, 180],
    ...APPLE,
    sourceUrl: appStore(1146560473),
    retrieved: RETRIEVED,
    label: 'Messages',
  },
  {
    id: 'app.ios.settings',
    file: 'icons/ios/settings.png',
    kind: 'app-icon',
    sizes: [120, 180],
    ...APPLE,
    sourceUrl: 'https://support.apple.com/guide/iphone/welcome/ios',
    retrieved: RETRIEVED,
    label: 'Settings',
  },

  // Android — launcher (adaptive mask applied by the UI)
  {
    id: 'app.android.chrome',
    file: 'icons/play/chrome.png',
    kind: 'app-icon',
    sizes: [96, 144],
    ...GOOGLE,
    sourceUrl: play('com.android.chrome'),
    retrieved: RETRIEVED,
    label: 'Chrome',
  },
  {
    id: 'app.android.github',
    file: 'icons/play/github.png',
    kind: 'app-icon',
    sizes: [96, 144],
    ...GITHUB,
    sourceUrl: play('com.github.android'),
    retrieved: RETRIEVED,
    label: 'GitHub',
  },
  {
    id: 'app.android.files',
    file: 'icons/play/files.png',
    kind: 'app-icon',
    sizes: [96, 144],
    ...GOOGLE,
    sourceUrl: play('com.google.android.apps.nbu.files'),
    retrieved: RETRIEVED,
    label: 'Files',
  },
  {
    id: 'app.android.keep',
    file: 'icons/play/keep.png',
    kind: 'app-icon',
    sizes: [96, 144],
    ...GOOGLE,
    sourceUrl: play('com.google.android.keep'),
    retrieved: RETRIEVED,
    label: 'Keep Notes',
  },
  {
    id: 'app.android.gmail',
    file: 'icons/play/gmail.png',
    kind: 'app-icon',
    sizes: [96, 144],
    ...GOOGLE,
    sourceUrl: play('com.google.android.gm'),
    retrieved: RETRIEVED,
    label: 'Gmail',
  },
  {
    id: 'app.android.settings',
    file: 'icons/android/settings.png',
    kind: 'app-icon',
    sizes: [96, 144],
    ...GOOGLE,
    sourceUrl: 'https://source.android.com/',
    retrieved: RETRIEVED,
    label: 'Settings',
  },

  // Boot marks
  {
    id: 'system.apple-logo',
    file: 'icons/system/apple-logo.svg',
    kind: 'system-icon',
    monochrome: true,
    ...APPLE,
    sourceUrl: commons('Apple logo black.svg'),
    retrieved: RETRIEVED,
    label: 'Apple logo',
  },
  {
    id: 'system.windows-logo',
    file: 'icons/system/windows-logo-mark.svg',
    kind: 'system-icon',
    ...MICROSOFT,
    sourceUrl: commons('Windows 11 logo.svg'),
    retrieved: RETRIEVED,
    label: 'Windows logo',
  },
  // Windows 11 shell artwork: the folder (desktop, File Explorer) and This PC (plans/windows/surfaces/desktop).
  {
    id: 'system.windows-folder',
    file: 'icons/windows/folder-11.png',
    kind: 'system-icon',
    sizes: [48, 96],
    ...MICROSOFT,
    sourceUrl: 'https://github.com/blueedgetechno/win11React/tree/master/public/img/icon/win',
    retrieved: RETRIEVED,
    label: 'Windows folder',
  },
  {
    id: 'system.windows-this-pc',
    file: 'icons/windows/this-pc-11.png',
    kind: 'system-icon',
    sizes: [48, 96],
    ...MICROSOFT,
    sourceUrl: 'https://github.com/blueedgetechno/win11React/tree/master/public/img/icon/win',
    retrieved: RETRIEVED,
    label: 'This PC',
  },
  {
    id: 'system.windows-recycle-bin',
    file: 'icons/windows/recycle-bin.png',
    kind: 'system-icon',
    sizes: [48, 96],
    ...MICROSOFT,
    sourceUrl: 'https://github.com/blueedgetechno/win11React/tree/master/public/img/icon/win',
    retrieved: RETRIEVED,
    label: 'Recycle Bin',
  },
  {
    id: 'system.android-boot',
    file: 'icons/android/android-head.svg',
    kind: 'system-icon',
    ...GOOGLE,
    sourceUrl: 'https://developer.android.com/distribute/marketing-tools/brand-guidelines',
    retrieved: RETRIEVED,
    label: 'Android robot',
  },

  // Profile avatars
  {
    id: 'avatar.recruiter',
    file: 'netflix/avatar-blue.png',
    kind: 'avatar',
    sizes: [100, 200],
    ...NETFLIX,
    sourceUrl: 'https://github.com/Sandhit06/Netflix-Portfolio',
    retrieved: RETRIEVED,
    label: 'Blue profile avatar',
  },
  {
    id: 'avatar.developer',
    file: 'netflix/avatar-grey.png',
    kind: 'avatar',
    sizes: [100, 200],
    ...NETFLIX,
    sourceUrl: 'https://github.com/Sandhit06/Netflix-Portfolio',
    retrieved: RETRIEVED,
    label: 'Grey profile avatar',
  },
  {
    id: 'avatar.adventurer',
    file: 'netflix/avatar-yellow.png',
    kind: 'avatar',
    sizes: [100, 200],
    ...NETFLIX,
    sourceUrl: 'https://github.com/Sandhit06/Netflix-Portfolio',
    retrieved: RETRIEVED,
    label: 'Yellow profile avatar',
  },
  {
    id: 'avatar.designer',
    file: 'netflix/avatar-red.png',
    kind: 'avatar',
    sizes: [100, 200],
    ...NETFLIX,
    sourceUrl: 'https://github.com/Sandhit06/Netflix-Portfolio',
    retrieved: RETRIEVED,
    label: 'Red profile avatar',
  },
  {
    id: 'avatar.guest',
    file: 'netflix/avatar-green.png',
    derivedFrom: 'netflix/avatar-blue.png',
    transform: 'hue-green',
    kind: 'avatar',
    sizes: [100, 200],
    ...NETFLIX,
    sourceUrl: 'https://github.com/Sandhit06/Netflix-Portfolio',
    retrieved: RETRIEVED,
    label: 'Green profile avatar',
  },

  // iOS Home and Lock Screen wallpaper: the iPhone 16 (Ultramarine) — the owner's choice (plans/ios/01 "Wallpaper").
  {
    id: 'wallpaper.ios',
    file: 'wallpapers/ios-iphone16-ultramarine.jpg',
    kind: 'wallpaper',
    owner: 'Apple Inc.',
    terms:
      'Artwork of Apple Inc. (the iPhone 16 Ultramarine wallpaper); used referentially to recreate the iPhone Home Screen. No affiliation.',
    sourceUrl: 'https://www.iclarified.com/94911/download-the-official-iphone-16-wallpaper-here',
    retrieved: '2026-09-23',
    label: 'iPhone 16 wallpaper (Ultramarine)',
  },

  // Intro sound (fetched on idle, decoded on the Hello tap)
  {
    id: 'audio.intro',
    file: 'netflix/intro.mp3',
    kind: 'audio',
    ...NETFLIX,
    sourceUrl: 'https://github.com/Sandhit06/Netflix-Portfolio',
    retrieved: RETRIEVED,
    label: 'Intro sound',
  },
];
